from dotenv import load_dotenv
import os

load_dotenv()

# global
RELEASE = not os.getenv("RELEASE") is None
IMAGE_STORAGE_PATH = os.getenv("IMAGE_STORAGE_PATH")
FRONTEND_HOST = os.getenv("FRONTEND_HOST")

# format
EMAIL_FORMAT = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"
NAME_FORMAT = r"^[가-힣A-Za-z0-9_]{1,32}$"
PASSWORD_FORMAT = r"^[A-Za-z0-9!@#$_.?-]{8,}$"
DECIMAL_FORMAT = r"^[0-9]+(\.[0-9]+)?$"

# constant record
SIGN_UP_TOKEN_EXPIRY_PERIOD = 10 * 60 # 10 min
LOG_IN_TOKEN_EXPIRY_PERIOD = 24 * 60 * 60  # 1 day

# database
DB_URL = os.getenv("DB_URL")

# mail
SMTP_SERVER_ADDRESS = os.getenv("SMTP_SERVER_ADDRESS")
SMTP_PORT = os.getenv("SMTP_PORT")
SMTP_MAIL_ADDRESS = os.getenv("SMTP_MAIL_ADDRESS")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

# crypto_tools
FERNET_KEY = os.getenv("FERNET_KEY")
PASSWORD_HASHING_PAPPER = os.getenv("PASSWORD_HASHING_PAPPER").encode()
ID_HASHING_SALT = os.getenv("ID_HASHING_SALT")
JWT_KEY = os.getenv("JWT_KEY")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")

# error details
INVALID_ID = "INVALID_ID"
INVALID_TOKEN = "INVALID_TOKEN"
EXPIRED_TOKEN = "EXPIRED_TOKEN"
ALREADY_REGISTERED = "ALREADY_REGISTERED"
UNREGISTERED = "UNREGISTERED"
INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
NOT_LOGGED_IN = "NOT_LOGGED_IN"
NO_AUTHORITY = "NO_AUTHORITY"
WRONG_IMAGE_FORMAT = "WRONG_IMAGE_FORMAT"
NO_AUTHORITY = "NO_AUTHORITY"

# cookies names
COOKIE_LOG_IN = "login"